name: Karawang Env Pipeline

# Kapan jadwal ini berjalan?
on:
  schedule:
    - cron: "0 0 * * *" # Berjalan setiap jam 00:00 UTC (sekitar jam 7 pagi WIB)
  workflow_dispatch: # Memunculkan tombol "Run Workflow" agar kamu bisa jalankan manual kapan saja

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest # Meminjam server Linux gratis dari GitHub

    steps:
      # 1. Mengambil kodemu dari GitHub
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Menyiapkan Python (Karena Ingestion kita pakai Python)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Memberikan akses Google Cloud ke GitHub
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # 4. Menginstal alat Bruin CLI & Mendaftarkannya ke Sistem
      - name: Install Bruin
        run: |
          curl -L https://github.com -o bruin
          chmod +x bruin
          sudo mv bruin /usr/local/bin/

      # 5. Mengeksekusi Pipa Data secara End-to-End!
      - name: Run Bruin Pipeline
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_GHA_CREDS_PATH
          bruin run
